### ISSUE TITLE
Interface display issues

### ISSUE THREAD

**Issue by dqwiki** [UTRS/utrs#52] opened 2015-11-18 22:24 UTC
Notice: Undefined offset: 0 in /usr/UTRSgit/utrs/public_html/src/noticeObject.php on line 140
Generated on appeal.php

No clue what it's about, investigating

**Comment by Salvidrim** [comment] 2015-11-18 22:26
Think it may have to do with the sitenotice -- it says NoticeObject in the error and I don't recall seeing this before I tweaked the sitenotice earlier.

Sorry if I worked things. Lemme know what it was if it's something I did

Date: Wed, 18 Nov 2015 14:24:46 -0800

**Comment by dqwiki** [comment] 2015-11-18 22:30
Ya it's definitely something to do with the site notice...i'm just trying to figure what the trip is.

**Comment by Salvidrim** [comment] 2015-11-18 22:31
The only big change I can think of is that the color uses a hexcode and a pound sign instead of a wordcode, so maybe the poundsign messes things up? Just throwing ideas


Sent from Outlook Mobile






On Wed, Nov 18, 2015 at 2:30 PM -0800, "DeltaQuad" <notifications@github.com> wrote:





Ya it's definitely something to do with the site notice...i'm just trying to figure what the trip is.

---

**Comment by dqwiki** [comment] 2015-11-18 22:32
Removed that, didn't help.

**Comment by dqwiki** [comment] 2015-11-18 22:38
By screwing with the live code I echoed $syntaxCodes[$j] I got:

{[/green] Notice: Undefined offset: 0 in /usr/UTRSgit/utrs/public_html/src/noticeObject.php on line 140 Notice: Undefined offset: 0 in /usr/UTRSgit/utrs/public_html/src/noticeObject.php on line 141 [/red][/green][/red][/green]/

**Comment by Salvidrim** [comment] 2015-11-18 22:40
Looks like the issue is the color tag green inside the link produced by curly brackets? Plausible. Does putting the color tags outside the curly brackets make the default linkformat (blue) override it?


Anyways its not a big deal if the link isn't green, if its causing issues just let it default to blue


~ Ben / Salvidrim

[sent from Outlook Mobile on a Nexus 5]






On Wed, Nov 18, 2015 at 2:38 PM -0800, "DeltaQuad" <notifications@github.com> wrote:





By screwing with the live code I echoed $syntaxCodes[$j] I got:

{[/green] Notice: Undefined offset: 0 in /usr/UTRSgit/utrs/public_html/src/noticeObject.php on line 140 Notice: Undefined offset: 0 in /usr/UTRSgit/utrs/public_html/src/noticeObject.php on line 141 [/red][/green][/red][/green]/

---

**Comment by dqwiki** [comment] 2015-11-18 22:44
So apparently we can't have formatting changes surrounding a link. Inside or outside. A new fix to this is something to look forward to in the future.

**Comment by Salvidrim** [comment] 2015-11-18 22:45
I've always been good an uncovering obscure bugs LMAO


~ Ben / Salvidrim

[sent from Outlook Mobile on a Nexus 5]






On Wed, Nov 18, 2015 at 2:44 PM -0800, "DeltaQuad" <notifications@github.com> wrote:





So apparently we can't have formatting changes surrounding a link. Inside or outside. A new fix to this is something to look forward to in the future.

---

**Comment by Salvidrim** [comment] 2015-11-22 08:38
duplicate of #18

**Closed** 2015-11-22 08:40 UTC
Labels: duplicate/invalid
